### ISSUE TITLE
Joint trajectory server might cause unexpected movements when disabling and enabling the robot

### ISSUE THREAD

**Issue by Petrox** [RethinkRobotics/baxter_interface#65] opened 2015-09-13 17:27 UTC
Scenario:
 
 - robot enabled
 - using moveit to create a plan
 - execution of the plan through moveit  (or directly through joint trajectory server)
 - robot reaches end pose
 - program quits (planned or via fault)
 - robot gets disabled
 - arms are released, so they slowly reach a relaxed position
 - robot gets enabled (the current user might not even know about the previous events, he just knows the robot is disabled)
 - joint trajectory server tries to reach the last goal in the shortest time possible without checking the distance, the speed, or anything, just blindly exploding to the target pose.
 - arms might hit each other, the environment or people

Note: this is a high speed, uncontrolled movement, the fastest I've seen Baxter moving ever, so using the maximum torque probably at the limits of mechanics.  This usecase might even reduce the mechanical parts lifetime.
 
Workaround1:
 when disabling the robot one could kill the joint trajectory server, and restart it, to start clean.

Workaround2:
 Before enabling the robot, a program could use a TF listener (or other method), to get the current joint state, and command the joint trajectory server to that joint state, so when enabling the robot the joint trajectory server would move to there, not the dangerous remote one.

Suggested solution:
 - joint trajectory server should listen on robot enabled / disabled state changes, and forget to

**Comment by rethink-imcmahon** [comment] 2015-09-22 15:42
Thank you for pointing out this issue, @Petrox. I need to verify the senario, but I am already thinking about solutions. Operating under the premise that I can replicate this, I am thinking this is caused by the fact that the JTAS operates under raw joint position mode by default. This gives full power to MoveIt to calculate trajectories and calculate the Feed Forward velocities and accelerations for fast, accurate movements, and disables some speed limits that would otherwise throttle the arms' speeds. I am thinking the solution will be to simply add a subscriber to the JTAS for the enable topic and clear the current trajectory if a disable is set. I will update you on my progress here.

**Comment by atenpas** [comment] 2015-10-26 20:22
Same problem here, when using the JTA directly though the action server interface.

**Comment by rethink-imcmahon** [comment] 2015-12-08 15:54
Resolved by #69

**Closed by rethink-imcmahon** 2015-12-08 15:54 UTC
